from cogs import whatdidimiss, stop, misc
from services.config import CONFIG
from services import utils

s = "What the fuck did you just fucking say about me, you little bitch? Ill have you know I graduated top of my class in the Navy Seals, and Ive been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and Im the top sniper in the entire US armed forces. You are nothing to me but just another target. I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth, mark my fucking words. You think you can get away with saying that shit to me over the Internet? Think again, fucker. As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. Youre fucking dead, kid. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and thats just with my bare hands. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable ass off the face of the continent, you little shit. If only you could have known what unholy retribution your little clever comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldnt, you didnt, and now youre paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. Youre fucking dead, kiddo. ";
s2 = "I saw Donald Trump at a grocery store in D.C yesterday. I told him how cool it was to meet him in person, but I didn’t want to be a douche and bother him and ask him for photos or anything. He said, “Oh, like you’re doing now?” I was taken aback, and all I could say was “Huh?” but he kept cutting me off and going “huh? huh? huh?” and closing his hand shut in front of my face. I walked away and continued with my shopping, and I heard him chuckle as I walked off. When I came to pay for my stuff up front I saw him trying to walk out the doors with like fifteen Milky Ways in his hands without paying. The girl at the counter was very nice about it and professional, and was like “Sir, you need to pay for those first.” At first he kept pretending to be tired and not hear her, but eventually turned back around and brought them to the counter. When she took one of the bars and started scanning it multiple times, he stopped her and told her to scan them each individually “to prevent any electrical infetterence,” and then turned around and winked at me. I don’t even think that’s a word. After she scanned each bar and put them in a bag and started to say the price, he kept interrupting her by yawning really loudly. After paying for the Milky Ways he proceeded to leave the store and throw all of them in the garbage. Haven't seen him since. "
s3 = "I wore a mask at Target today. Three of my lungs collapsed as I got carbon monoxide poisoning from breathing in my own bacteria. A brave patriot wearing an Affliction shirt, a MAGA hat, and sweet wrap around sunglasses saved me by giving me CPR. I thanked him and asked if he was a doctor and he said \"who needs doctors when we have our fellow Americans, the ones who are here legally I mean.\" I hugged him and threw my mask on the ground. The Star Spangled Banner played on the speaker system as everyone in the store ripped off their masks and threw them on the ground, chanting \"down with communism!\" God, Jesus, and all the angels looked down upon us from Heaven and clapped."
a = "<:tipha:72430265361764744> "
b = "<:long:73335589948127266> "
c = u"\U0001F60A" + " "+ u"\U0001F60E" + " "
words = dict()
stop = CONFIG["commands"]["whatdidimiss"]["stopwords"]
utils.add_frequency(words, s + s2 + s3 + a*10 + b*10 + c*2, stop, True)
f = open("navy.png", "wb")
f.write(whatdidimiss.create_wordcloud(words).read())
f.close()